DROP DATABASE IF EXISTS tiendaonline;
CREATE DATABASE tiendaonline;
USE tiendaonline;

CREATE TABLE Usuarios(
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(255) NOT NULL,
	contraseña VARCHAR(255) NOT NULL CHECK (CHAR_LENGTH(contraseña) >=8),
	nombre VARCHAR(255) NOT NULL
);

CREATE TABLE Empleados(
	id INT PRIMARY KEY AUTO_INCREMENT,
	usuarioId INT NOT NULL, 
	salario DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (usuarioId) REFERENCES Usuarios(id) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE Clientes(
	id INT PRIMARY KEY AUTO_INCREMENT,
	usuarioId INT NOT NULL,
	direccionEnvio VARCHAR(255) NOT NULL, 
	codigoPostal VARCHAR(10) NOT NULL,
	fechaNacimiento VARCHAR(10) NOT NULL,
	FOREIGN KEY (usuarioId) REFERENCES Usuarios(id) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
);

CREATE TABLE Pedidos(
	id INT PRIMARY KEY AUTO_INCREMENT,
	fechaRealizacion DATE NOT NULL,
	fechaEnvio DATE,
	direccionEntrega VARCHAR(255) NOT NULL,
	comentarios TEXT,
	clienteId INT NOT NULL,
	empleadoId INT,
	FOREIGN KEY (clienteId) REFERENCES Clientes(id)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT,
	FOREIGN KEY (empleadoId) REFERENCES Empleados(id)
		ON DELETE SET NULL
		ON UPDATE SET NULL
);

CREATE TABLE TiposProducto(
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL
);

CREATE TABLE Productos(
	id INT PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(255) NOT NULL,
	descripcion VARCHAR(255),
	precio DECIMAL(10,2) NOT NULL CHECK (precio>=0),
	tipoProductoId INT NOT NULL,
	puedeVenderseAMenores BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (tipoProductoId) REFERENCES TiposProducto(id)
);

CREATE TABLE LineasPedido(
	id INT PRIMARY KEY AUTO_INCREMENT,
	pedidoId INT NOT NULL,
	productoId INT NOT NULL,
	unidades INT NOT NULL CHECK (unidades>0 AND unidades <=100),
	precioUnitario DECIMAL(10,2) NOT NULL,
	FOREIGN KEY (pedidoId) REFERENCES Pedidos(id) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE,
	FOREIGN KEY (productoId) REFERENCES Productos(id)
);